ImmovableWall_2.0
Calvin-Davidson/Mythe pull request #75
Opened 2021-06-02 14:37 UTC by TravelingWitch

Hier is de nieuw Immovable wall ik hoop dat deze wel werk met de shader!

2021-06-02 14:55 UTC, Calvin-Davidson requested changes
De muur is niet repeating en kan ook niet in het midden van het level geplaats worden want 2 kanten zijn flat

2021-06-10 10:50 UTC, Ingmar-van-Busschbach requested changes
3 out of 4 pillars still have internal geometry

2021-06-14 11:04 UTC, Ingmar-van-Busschbach approved these changes

2021-06-14 11:05 UTC, Ingmar-van-Busschbach approved these changes

2021-06-14 11:06 UTC, Calvin-Davidson approved these changes

2021-06-14 11:06 UTC, merged